
version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: hrms-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: demo123
      MONGO_INITDB_DATABASE: hrms
    volumes:
      - mongo-data:/data/db
    networks:
      - hrms-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: hrms-api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGODB_URI: mongodb://admin:demo123@mongodb:27017/hrms?authSource=admin
      JWT_SECRET: demo-jwt-secret-change-in-prod
      AI_SERVICE_URL: http://ai-service:8000
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - hrms-network
    command: npm run dev

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: hrms-ai
    ports:
      - "8001:8000" 
    environment:
      PYTHONUNBUFFERED: 1
      CHROMA_PERSIST_DIR: /app/chroma_data
    volumes:
      - ./ai-service:/app
      - chroma-data:/app/chroma_data
    networks:
      - hrms-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo-data:
  chroma-data:

networks:
  hrms-network:
    driver: bridge